### ISSUE TITLE
The demo is broken

### ISSUE THREAD

**Issue by kasbah** [manyfold3d/manyfold#3265]
**Describe the bug**
The demo at https://try.manyfold.app/ seems to be broken

**To Reproduce**
1. Go to https://try.manyfold.app/
2. See error

**Screenshots**

![image](https://github.com/user-attachments/assets/2fde30bb-ade6-4f1c-8a4f-23a84e823e9a)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser
    - Firefox 132.0.2 
    - Chromium 131.0.6778.69

**Comment by Floppy** [comment]
Fixed now - thanks for letting me know, I really should set up some sort of monitoring!

**Comment by kasbah** [comment]
It seems to be broken again. When it was fixed previously it worked again in Chromium (without extensions) but was still broken in my Firefox (with various blocking extensions installed).

**Comment by Floppy** [comment]
Thanks; it keeps happening, I'll look at it tomorrow.

**Comment by kasbah** [comment]
Seems better again but there is still an issue remaining. I did some more debugging:

- If I click the link on the GitHub readme I get the "not redirecting properly" error, no matter what browser
- If I click the link on manyfold.app it works fine
- If I copy and paste the link it works fine

**Comment by Floppy** [comment]
Thanks!

**Comment by Floppy** [comment]
Hah, that *is* exactly the problem reported in #3260. Hmm.

**Comment by Floppy** [comment]
Well, this was an interesting one in which I learned something new about browser security. I've pushed a fix in v0.91.1 that seems to fix it for me, hopefully it will for you too.

**Comment by kasbah** [comment]
Yep, seems good now. Can you summarise briefly what it was? Just out of curiosity.

**Comment by Floppy** [comment]
Annoyingly the demo is still falling over regularly because of an [intermittent SQLite I/O error](https://github.com/manyfold3d/try-manyfold/issues/1) though. At least I've got monitoring on it now so when it happens, I can bring it back as soon as I'm able.
